config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :lists, only: [:index, :new, :create, :show] do
    resources :bookmarks, only: [:new, :create]
  end
  resources :bookmarks, only: [:destroy], as: :delete_bookmark

  # Read all
  # get 'lists/:id/bookmarks/new', to:'lists#index'

  # # Create new
  # get "lists/new", to: "lists#new"
  # post "lists", to: "lists#create"

  # # Read one
  # get 'lists/:id', to:'lists#show'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates :movie, presence: true, uniqueness: { scope: :list }
  validates :comment, presence: true, length: { minimum: 6 }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController

  before_action :set_list, only: %i[new create]

  def new
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to list_path(@bookmark.list), status: :see_other
  end

  private

  def set_list
    @list = List.find(params[:list_id])
  end

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show]

  def index
    @lists = List.all
  end

  def show
    @movies = @list.movies
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def list_params
    params.require(:list).permit(:name)
  end

  def set_list
    @list = List.find(params[:id])
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/bookmarks/new.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-12 col-lg-6">
      <h1>New bookmark</h1>
      <%= simple_form_for [@list, @bookmark] do |f| %>
        <%= f.input :comment %>
        <%= f.association :movie %>
        <%= f.submit "Submit bookmark", class: "btn btn-primary mb-5" %>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Amatic+SC&family=Assistant:wght@500&family=Cardo&family=Cormorant+Garamond:wght@300&family=Montserrat:wght@200;300&family=Open+Sans:wght@300&family=Raleway:wght@300;400&display=swap" rel="stylesheet">
  </head>

  <body>
    <%= yield %>
  </body>

  <footer style>
  </footer>
</html>

app/views/lists/_form.html.erb
<%= simple_form_for(list) do |f| %>
  <%= f.input :name %>
  <%= f.submit %>
<% end %>

app/views/lists/index.html.erb
<div id="banner">
  <div class="container" class="d-flex justify-content-center">
    <h1>Handle your lists </h1>
  </div>
</div>
<div class="container">
  <h2>Your categories </h2>
  <div class="btn">
    <%= link_to 'Create movie list', new_list_path, class: "btn btn-secondary" %>
  </div>
  <ul class='cards'>
    <% @lists.each do |list| %>
      <li class="card" ><%= link_to list.name, list_path(list), class:"text" %></li>
    <% end %>
  </ul>
</div>
<div id="footer">
</div>

app/views/lists/new.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-12 col-lg-6">
      <%= simple_form_for(@list) do |f| %>
        <%= f.input :name %>
        <%= f.submit %>
      <% end %>

      <%= link_to 'Back to list', lists_path(@lists), class: "btn btn-primary mt-3" %>
    </div>
  </div>
</div>

app/views/lists/show.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-12 col-lg-6">
      <h2><%= @list.name %></h2>
        <ul class="list-group">
          <% @list.bookmarks.each do |bookmark| %>
          <img src=<%="#{bookmark.movie.poster_url}"%>>
            <li class="list-group-item"><%= bookmark.movie.title %>
            <li class="list-group-item"><%= bookmark.comment %></li>
            <li class="list-group-item">
             <%= link_to "Delete",
            delete_bookmark_path(bookmark), class:"btn btn-secondary mt-3",
            data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}
             %>
            </li>
          <% end %>
          </ul>
      <p><%= link_to "Add bookmarks", new_list_bookmark_path(@list), class:"btn btn-info mt-3" %></p>
      <p><%= link_to "Back", lists_path(@list), class:"btn btn-primary mt-3" %></p>
    </div>
  </div>
</div>